[project]
name = "fund-distribution"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.2"
dependencies = [
    "python-dotenv>=1.1.1",
    "web3>=7.13.0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
    "jedi>=0.19.2",
]
